@startuml

class User {
  String id
  String name
  Array known_chords
  tuneInstrument()
  --encrypted--
  String password
}

class Instrument {
  String id
  String name
  Tuning tuning
}

class Note {
  String instrument_id
  Number audio_frequency
  String name e.g. ("Am7")
}

class Tuning {
  String id
  { notes: Array.<Note> }
  String name (e.g. "gCEA")
}

Tuning o-- Note
Instrument *-- Tuning

note "These classes are what go into creating the Tuner\n which is a front-end class" as N1

@enduml